### ISSUE TITLE
have a hyperlink to mempool.space when clicking on the txid of a successful round

### ISSUE THREAD

**Issue by MarnixCroes** [turbolay/LiquiSabi#1]
currently you can copy the txid, I think many people have the intention to then view tx's in mempool.space or another block explorer.
Having a hyperlink where clicking on the txid directs to mempool.space with the right tx details would be nice

**Comment by turbolay** [comment]
I will do it. I will also open a new repo for the webfront

**Comment by MarnixCroes** [comment]
bueno
